"""deletingsummary.text

Revision ID: 437f79ec4acc
Revises: 
Create Date: 2020-01-23 15:00:18.375713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437f79ec4acc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('text', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
