"""adding back summary.text

Revision ID: 89d2c54ebe0a
Revises: 437f79ec4acc
Create Date: 2020-01-23 15:01:43.791506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d2c54ebe0a'
down_revision = '437f79ec4acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('text', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'text')
    # ### end Alembic commands ###
