"""adding summary.lang_code and summary.summary_marker as nullable

Revision ID: d3cc2fb2d9dd
Revises: 89d2c54ebe0a
Create Date: 2020-01-23 16:41:57.146104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cc2fb2d9dd'
down_revision = '89d2c54ebe0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summaries', sa.Column('lang_code', sa.String(length=5), nullable=True))
    op.add_column('summaries', sa.Column('summary_marker', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('summaries', 'summary_marker')
    op.drop_column('summaries', 'lang_code')
    # ### end Alembic commands ###
